name: server
services:
    mysql:
        ports:
            - 3306:3306
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234
        image: mysql
    phpmyadmin:
        ports:
            - 8080:80
        links:
            - mysql:db
        container_name: phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=1234
        image: phpmyadmin